### ISSUE TITLE
Missing vocab.chatbot.16384 file

### ISSUE THREAD

**Issue by hannes-marais-edmodo** [ricsinaruto/Seq2seqChatbots#10]
Running the generate command fails with a missing file.

$ python t2t_csaky/main.py --mode=generate_data
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Program is running in data generation mode.
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/util/tf_inspect.py:75: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  return _inspect.getargspec(target)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
INFO:tensorflow:Importing user module t2t_csaky from path /home/hannes/Seq2seqChatbots
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/utils/registry.py:180: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
  args, varargs, keywords, _ = inspect.getargspec(rhp_fn)
INFO:tensorflow:Generating problems:
    daily:
      * daily_dialog_chatbot
INFO:tensorflow:Generating data for daily_dialog_chatbot.
:::MLPv0.5.0 transformer 1542920333.001461029 (/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/data_generators/text_problems.py:306) preproc_tokenize_training
Traceback (most recent call last):
  File "/home/hannes/anaconda3/envs/tf_gpu/bin/t2t-datagen", line 28, in <module>
    tf.app.run()
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/hannes/anaconda3/envs/tf_gpu/bin/t2t-datagen", line 23, in main
    t2t_datagen.main(argv)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/bin/t2t_datagen.py", line 198, in main
    generate_data_for_registered_problem(problem)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/bin/t2t_datagen.py", line 260, in generate_data_for_registered_problem
    problem.generate_data(data_dir, tmp_dir, task_id)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/data_generators/text_problems.py", line 306, in generate_data
    self.generate_encoded_samples(data_dir, tmp_dir, split)), paths)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/data_generators/text_problems.py", line 263, in generate_encoded_samples
    encoder = self.get_or_create_vocab(data_dir, tmp_dir)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/data_generators/text_problems.py", line 239, in get_or_create_vocab
    replace_oov=self.oov_token)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/data_generators/text_encoder.py", line 311, in __init__
    self._init_vocab_from_file(vocab_filename)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensor2tensor/data_generators/text_encoder.py", line 347, in _init_vocab_from_file
    tokens = [token.strip() for token in f.readlines()]
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 188, in readlines
    self._preread_check()
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 85, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/hannes/anaconda3/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: data_dir/DailyDialog/no_stop_words/vocab.chatbot.16384; No such file or directory

**Comment by ricsinaruto** [comment]
Hi,

For some reason this doesn't work as before but has a very easy solution.

1. Create an empty file with the same name at the location where you have the missing file.
2. Run the program, it will fail again but now the vocab file will be built.
3. Delete everything from that directory except the vocab.chatbot.16384 file.
4. Run the program again, now it will build all the data correctly.

Let me know if it works or if you need further help!

**Comment by ricsinaruto** [comment]
This should now be solved by #12 so I'm closing the issue.
The vocab file is automatically generated now during data generation.
