### ISSUE TITLE
module 'tensor2tensor.utils.registry' has no attribute 'Modalities'

### ISSUE THREAD

**Issue by ffffuturexu** [ricsinaruto/Seq2seqChatbots#11]
`File "/home/Network/Seq2seqChatbots/t2t_csaky/problems/word_chatbot.py", line 137, in hparams
    "inputs": (registry.Modalities.SYMBOL, source_vocab_size)}
AttributeError: module 'tensor2tensor.utils.registry' has no attribute 'Modalities'
`
The class 'Modalities' has been removed from 'tensor2tensor.utils.registry' since t2t v1.11.0.

**Comment by ricsinaruto** [comment]
Thanks for bringing this to my attention. Unfortunately, currently I don't have plans to upgrade the repo to work with newer t2t versions. If you want to run the code please use t2t versions prior to v1.11.

**Comment by ricsinaruto** [comment]
I updated the code, it should now work with the newest tensorflow and tensor2tensor versions (#12 )
I will close this, but please reopen if there are still issues on your side.
