### ISSUE TITLE
AttributeError: 'DailyDialogChatbot' object has no attribute 'already_shuffled'

### ISSUE THREAD

**Issue by momo1986** [ricsinaruto/Seq2seqChatbots#18]
Hello, thanks for sharing.

I download the data and find the problem when I try to run:
python t2t_csaky/main.py --mode=generate_data

How can I resolve this issue?

Thanks & Regards!

**Comment by ricsinaruto** [comment]
Hi,

It's probably because of some update in the tensor2tensor module, please try an older version.

**Comment by momo1986** [comment]
Could you provide an ideal tensorflow version and tensor2tensor version to run this program, always exists version inconsistency.
Thanks, @ricsinaruto

**Comment by ricsinaruto** [comment]
I'm closing this issue with the same answer as #20
