### ISSUE TITLE
Not able to setup environment using requirement.txt!

### ISSUE THREAD

**Issue by VikasRajashekar** [ricsinaruto/Seq2seqChatbots#20]
Did someone succeed in setting up the environment? I get various compatibility issues when I tried to set up. Does any one know the version of tensor2tensor and Tensorflow to be used to set it up?

**Comment by ricsinaruto** [comment]
I suggest using the original tensor2tensor repo instead of this one, because I included the same datasets there, and it's probably more up to date.
